#!/bin/bash

# Setup MCP (Model Context Protocol) integration with Logseq
# Enables direct Claude-Logseq communication

set -e

MCP_LOGSEQ_DIR="${HOME}/.claude/mcp-servers/logseq"
LOGSEQ_GRAPH_PATH="/media/dontpanic/1112-15D8"

show_help() {
    cat << 'EOF'
Setup MCP Integration with Logseq

USAGE:
    setup-mcp.sh [OPTIONS]

OPTIONS:
    --graph-path PATH   Path to logseq graph (default: /media/dontpanic/1112-15D8)
    --install-dir DIR   MCP server install directory (default: ~/.claude/mcp-servers/logseq)
    --port PORT         MCP server port (default: 3002)
    --help              Show this help

DESCRIPTION:
    Sets up MCP (Model Context Protocol) integration for seamless Claude-Logseq
    communication. This enables direct graph operations from Claude.

REQUIREMENTS:
    - Node.js and npm installed
    - Logseq desktop app with graph directory
    - Internet connection for downloading mcp-logseq

EXAMPLES:
    setup-mcp.sh
    setup-mcp.sh --graph-path "/custom/graph/path"
    setup-mcp.sh --port 3003
EOF
}

check_requirements() {
    echo "🔍 Checking requirements..."

    # Check Node.js
    if ! command -v node &> /dev/null; then
        echo "❌ Node.js not found"
        echo "Install Node.js: https://nodejs.org/"
        return 1
    fi

    # Check npm
    if ! command -v npm &> /dev/null; then
        echo "❌ npm not found"
        echo "npm should be installed with Node.js"
        return 1
    fi

    # Check git
    if ! command -v git &> /dev/null; then
        echo "❌ git not found"
        echo "Install git to download mcp-logseq"
        return 1
    fi

    echo "✅ Requirements satisfied"
    return 0
}

install_mcp_server() {
    local install_dir="$1"
    local graph_path="$2"

    echo "📥 Installing MCP Logseq server..."

    # Create install directory
    mkdir -p "$install_dir"

    # Clone mcp-logseq repository
    if [[ -d "$install_dir/mcp-logseq" ]]; then
        echo "📁 mcp-logseq already exists, updating..."
        cd "$install_dir/mcp-logseq"
        git pull origin main
    else
        echo "📥 Cloning mcp-logseq repository..."
        cd "$install_dir"
        git clone https://github.com/ergut/mcp-logseq.git
        cd mcp-logseq
    fi

    # Install dependencies
    echo "📦 Installing dependencies..."
    npm install

    # Create configuration
    echo "⚙️ Creating configuration..."
    cat > config.json << EOF
{
  "graph_path": "$graph_path",
  "server_port": 3002,
  "log_level": "info",
  "features": {
    "page_operations": true,
    "block_operations": true,
    "graph_queries": true,
    "file_operations": true
  }
}
EOF

    echo "✅ MCP server installed"
}

create_startup_script() {
    local install_dir="$1"
    local graph_path="$2"
    local port="$3"

    echo "📝 Creating startup script..."

    local script_path="$install_dir/start-mcp-logseq.sh"

    cat > "$script_path" << EOF
#!/bin/bash

# Logseq MCP Server Startup Script
# Auto-generated by setup-mcp.sh

set -e

MCP_DIR="$install_dir/mcp-logseq"
GRAPH_PATH="$graph_path"
PORT="$port"

echo "🚀 Starting Logseq MCP Server..."
echo "Graph: \$GRAPH_PATH"
echo "Port: \$PORT"

cd "\$MCP_DIR"

# Check if graph directory exists
if [[ ! -d "\$GRAPH_PATH" ]]; then
    echo "❌ Graph directory not found: \$GRAPH_PATH"
    exit 1
fi

# Start MCP server
npm start -- --graph-path "\$GRAPH_PATH" --port "\$PORT"
EOF

    chmod +x "$script_path"

    echo "✅ Startup script created: $script_path"
}

configure_claude_integration() {
    local install_dir="$1"
    local port="$2"

    echo "🔧 Configuring Claude integration..."

    local claude_config_dir="${HOME}/.claude"
    local mcp_config="$claude_config_dir/mcp-config.json"

    mkdir -p "$claude_config_dir"

    # Create or update MCP configuration
    local mcp_entry='{
  "logseq": {
    "type": "mcp-server",
    "url": "http://localhost:'"$port"'",
    "description": "Logseq Knowledge Graph Integration",
    "capabilities": [
      "page_management",
      "block_operations",
      "graph_queries",
      "relationship_analysis"
    ]
  }
}'

    # Create basic MCP config if it doesn't exist
    if [[ ! -f "$mcp_config" ]]; then
        echo '{
  "servers": {}
}' > "$mcp_config"
    fi

    # Add logseq server configuration
    local temp_config=$(mktemp)
    jq ".servers.logseq = $mcp_entry" "$mcp_config" > "$temp_config" && mv "$temp_config" "$mcp_config"

    echo "✅ Claude MCP configuration updated"
}

create_test_script() {
    local install_dir="$1"

    echo "🧪 Creating test script..."

    local test_script="$install_dir/test-mcp-integration.sh"

    cat > "$test_script" << 'EOF'
#!/bin/bash

# Test MCP Logseq Integration
# Verifies MCP server functionality

set -e

MCP_URL="${MCP_URL:-http://localhost:3002}"

echo "🧪 Testing MCP Logseq Integration"
echo "Server: $MCP_URL"

# Test server health
echo "  • Testing server health..."
if curl -s "$MCP_URL/health" > /dev/null; then
    echo "  ✅ Server is healthy"
else
    echo "  ❌ Server health check failed"
    exit 1
fi

# Test page creation
echo "  • Testing page creation..."
test_page_data='{
    "method": "create_page",
    "params": {
        "title": "MCP Test Page",
        "content": "# MCP Integration Test\n\nThis page was created via MCP to test integration.\n\nCreated: '"$(date)"'"
    }
}'

response=$(curl -s -X POST "$MCP_URL/rpc" \
    -H "Content-Type: application/json" \
    -d "$test_page_data")

if echo "$response" | grep -q "success"; then
    echo "  ✅ Page creation works"
else
    echo "  ❌ Page creation failed"
    echo "  Response: $response"
fi

# Test graph queries
echo "  • Testing graph queries..."
query_data='{
    "method": "query_graph",
    "params": {
        "query": "pages",
        "limit": 5
    }
}'

response=$(curl -s -X POST "$MCP_URL/rpc" \
    -H "Content-Type: application/json" \
    -d "$query_data")

if echo "$response" | grep -q "result"; then
    echo "  ✅ Graph queries work"
else
    echo "  ❌ Graph queries failed"
fi

echo ""
echo "🎉 MCP integration test complete!"
EOF

    chmod +x "$test_script"

    echo "✅ Test script created: $test_script"
}

main() {
    local graph_path="$LOGSEQ_GRAPH_PATH"
    local install_dir="$MCP_LOGSEQ_DIR"
    local port="3002"

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --help|-h)
                show_help
                exit 0
                ;;
            --graph-path)
                graph_path="$2"
                shift 2
                ;;
            --install-dir)
                install_dir="$2"
                shift 2
                ;;
            --port)
                port="$2"
                shift 2
                ;;
            *)
                echo "Unknown option: $1" >&2
                show_help >&2
                exit 1
                ;;
        esac
    done

    echo "🔧 Setting up MCP Integration with Logseq"
    echo "Graph: $graph_path"
    echo "Install: $install_dir"
    echo "Port: $port"
    echo ""

    # Run setup steps
    check_requirements || exit 1

    if [[ ! -d "$graph_path" ]]; then
        echo "❌ Graph path does not exist: $graph_path"
        echo "Please ensure your Logseq graph directory exists"
        exit 1
    fi

    install_mcp_server "$install_dir" "$graph_path"
    create_startup_script "$install_dir" "$graph_path" "$port"
    configure_claude_integration "$install_dir" "$port"
    create_test_script "$install_dir"

    echo ""
    echo "🎉 MCP Integration setup complete!"
    echo ""
    echo "Next steps:"
    echo "1. Start MCP server:"
    echo "   $install_dir/start-mcp-logseq.sh"
    echo ""
    echo "2. Test integration:"
    echo "   $install_dir/test-mcp-integration.sh"
    echo ""
    echo "3. Use with Claude:"
    echo "   The logseq skill can now use MCP for direct graph operations"
    echo ""
    echo "Configuration files:"
    echo "  • MCP Server: $install_dir/mcp-logseq/"
    echo "  • Claude Config: ~/.claude/mcp-config.json"
    echo "  • Startup Script: $install_dir/start-mcp-logseq.sh"
}

# Only run main if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi